// <auto-generated />
namespace VismaUtvikler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populate_ContactPersons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_ContactPersons));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171608190_populate_ContactPersons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
