// <auto-generated />
namespace VismaUtvikler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_CType_refrence_in_Customer_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_CType_refrence_in_Customer_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201810221659260_removed_CType_refrence_in_Customer_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
