// <auto-generated />
namespace VismaUtvikler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populate_CustomerTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_CustomerTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171547309_populate_CustomerTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
