// <auto-generated />
namespace VismaUtvikler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterd_CustomerClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterd_CustomerClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171955338_alterd_CustomerClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
