// <auto-generated />
namespace VismaUtvikler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Customer_Classes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Customer_Classes));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171545428_added_Customer_Classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
